### ISSUE TITLE
[BUG] Swapped audio chanels

### ISSUE THREAD

**Issue by mazazanwar** [ananjaser1211/FloydQ_Reports#223] opened 2020-12-05 21:27 UTC
**Describe the bug**
it's not my headphones, I'm sure the audio is swapped L/R => R/L
i tested it on games such as PUBG Mobile and Genshin Impact and of cause YouTube, it's the same story.
**To Reproduce**
I have ni idea how to reproduce this problem, but it wasn't present at first, I did clear the settings but that didn't help.
**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7 edge]
 - Model: [G935F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by mazazanwar** [comment] 2020-12-05 23:59
I reinstalled the rom and the problem was resolved, I think the bug is caused by one of the patches.

**Comment by ananjaser1211** [comment] 2020-12-07 06:27
> I reinstalled the rom and the problem was resolved, I think the bug is caused by one of the patches.

could you try patch 3 and tell me if the audio gets swapped (backup system so its easy to revert)

**Comment by mazazanwar** [comment] 2020-12-08 01:07
> > I reinstalled the rom and the problem was resolved, I think the bug is caused by one of the patches.
> 
> could you try patch 3 and tell me if the audio gets swapped (backup system_img so its easy to revert)

yes, it's confirmed. patch 3 "3rdpartyvol.zip" is what causes the bug, 
> but I also noticed that without the patch, the audio in some games especially Genshin Impact starts glitching/stuttering, so please keep this in mind when editing the patch,
>thank you guys for your great work.

**Comment by ananjaser1211** [comment] 2020-12-09 16:59
The glitching in genshin impact is not related to the patch, its a bug with the game and oneui 2.5 , i have the same bug on my galaxy S9+ and Note 8 running OneUI 2.5 (the bug did not exist in 2.1)

**Comment by mazazanwar** [comment] 2020-12-10 19:18
> The glitching in genshin impact is not related to the patch, its a bug with the game and oneui 2.5 , i have the same bug on my galaxy S9+ and Note 8 running OneUI 2.5 (the bug did not exist in 2.1)

what I mean is that the patch actually solves the problem not make it, the game's audio was glitching before I installed the patch, and after I installed it the glitching was gone.
the only issue I have now is the swapped audio channels "just imagine playing pubg with the wrong audio directions"

**Comment by ananjaser1211** [comment] 2020-12-11 15:57
hm you are right, if i use 2.1 libaudioflinger the glitches are gone, but yes the L/R is flipped. so not really a viable solution. will see what i can come up with

**Comment by mazazanwar** [comment] 2020-12-11 21:52
looking forward to it.

**Comment by ananjaser1211** [comment] 2021-01-11 00:03
Since this was caused by a now removed patch, ill close it, continue in #220 for updated patch (for 3rd party vol control which casued this bug) there is a better workaround. wont be using this patch anymore

**Closed by ananjaser1211** 2021-01-11 00:03 UTC
