### ISSUE TITLE
[BUG] Device Certification Not Passing

### ISSUE THREAD

**Issue by Panfuji** [ananjaser1211/FloydQ_Reports#301] opened 2023-07-28 23:09 UTC
**Describe the bug**
Describe your issue here. 
Device Certification is not passing possibly due to the new Play Integrity checks.

**To Reproduce**
1: Go to Play Store
2: Check Device Certification

**Expected behavior**
"Device is certified"

**Screenshots**
![Playstore](https://github.com/ananjaser1211/FloydQ_Reports/assets/42109501/099d370b-9df2-414b-af73-09c515387597)

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

**Additional context**
I'm not too sure what is going on behind the scenes with the new Play Integrity breaking device certification because of my lack of familiarity with the nitty gritty of android modding in general, but I hope this might help aid in an unrooted workaround. 

All experiments are done with clean install.

While unrooted and with SELinux Enforcing (checked with adb), it will not pass, even with a clean install, with avaliable hotfixes applied (GPS, Hotfix 1 and Hotfix 2), with CronosKernel v8.0, and after force stopping and clearing data on Google Play Store and Google Play Services.
![Playstore](https://github.com/ananjaser1211/FloydQ_Reports/assets/42109501/f1b8a6b4-43a6-4956-b583-8e5d0661942a)

With MagiskHide (v23), it will still not pass (ctsprofile fail)
![Notpass](https://github.com/ananjaser1211/FloydQ_Reports/assets/42109501/7256897f-0133-40a1-a3e3-fe6a2371654d)

However with Magisk v26 and the Shamiko module and kdrag0n's safetynet fix module modded by Displax, device certification will pass, as seen in the screenshot here. 
![Pass](https://github.com/ananjaser1211/FloydQ_Reports/assets/42109501/dbca3e7f-8bcc-4f2e-94c7-356595003f97)

Regardless of if its fixable or not, thank you for making this rom - I have been daily driving it for 3 years and its still going strong.

**Comment by LowSkillDeveloper** [comment] 2023-07-31 18:47
The same problem with this ROM, writes that the device is not certified in google play, and also does not pass the SafetyNet check. Root is not installed, and I do not want to put it. There are solutions or whether there will be an update, maybe hotfix?
Because of this, some applications do not install, such as the official ChatGPT application.

**Comment by LowSkillDeveloper** [comment] 2023-07-31 18:50
The same problem with this ROM, writes that the device is not certified in google play, and also does not pass the SafetyNet check. Root is not installed, and I do not want to put it. @ananjaser1211  there are solutions or whether there will be an update, maybe hotfix?
Because of this, some applications do not install, such as the official ChatGPT application.

**Comment by ananjaser1211** [comment] 2023-08-12 21:02
ideally we should only be failiing hardware backed attestation, my guess is the fingerprint props inside the ROM got too old, the alternative is to use magisk or replace the fingerprint in each build prop in the ROM, if you were to flash magisk, using kdragon sagetynet module should be enough, until if/when i find some time to patch or just full on update the rom

**Comment by Panfuji** [comment] 2023-08-23 12:53
Okay, as an experiment I've tried changing everything that was had "FVE1" which is the previous fingerprint to the new one which is FWB3, and the files that I have changed that I saw had the old fingerprints in it are (within the install zip) system/build.prop, floyd/vendor/build.prop, floyd/vendor/odm/etc/build.prop. I looked into the build.prop within floyd/odm/build.prop but didn't find anything that contain the fingerprint. I also applied the extra stuff in the end.sh file, which looks something like this:

# HACK : Set model no to N9 To preserve BASIC EVAL TYPE
    props=$props'
	ro.product.model=SM-G965N
	ro.product.odm.model=SM-G965N
	ro.product.system.model=SM-G965N
	ro.product.system_ext.model=SM-G965N
	ro.product.vendor.model=SM-G965N
	ro.product.product.model=SM-G965N
	ro.system.build.fingerprint=samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXSAFWB3:user/release-keys
	ro.vendor.build.fingerprint=samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXSAFWB3:user/release-keys
	ro.odm.build.fingerprint=samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXSAFWB3:user/release-keys
'
Then I clean flashed the phone with the zip. The device is still showing up as not certified. Am I missing something here or is it potentially an issue that requires more information?

**Comment by ananjaser1211** [comment] 2023-10-13 14:53
@Panfuji Sorry for late response, i just had time to work on the S7 again, i have rebased to FWB3 / 2023-02 and it does not fix the issue. the problem is not from the fingerprint, the problem seems to be from our BASIC_ATTEST hack we use (which is a patched keystore binary) this no longer works.

the keystore fix by kdragon uses magisk / zygisk to alter methods in framework.jar to fix safetynet. on my other projects i was able to implement the fix inside framework.jar, however on android 10 modifying framework.jar breaks boot. so for now i dont see any way to bring back safetynet without rooting with magisk and using zygisk.

**Comment by Panfuji** [comment] 2023-10-16 07:01
Thanks for the reply - Guess for now using root will be mandatory for passing device certifcation.

**Comment by ananjaser1211** [comment] 2023-10-16 14:13
Well some good news, while working on V8 i manaaged to fix safetynet once more by implementing the bypass inside framework, to my surprise i was able to make it work. 

I am still working on the new update, i dont know when it will be done, but i am updating alot of stuff that broke over time in the ROM, at the very least we can confirm that safety net will be fine.

![image](https://github.com/ananjaser1211/FloydQ_Reports/assets/25624482/7ce9c33f-3025-4439-916f-581a98116925)

**Comment by ananjaser1211** [comment] 2023-11-05 14:27
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172

**Closed by ananjaser1211** 2023-11-05 14:27 UTC
Labels: bug, High Priority, Fixed in next release
