### ISSUE TITLE
[BUG/Kernel] Random Freezing

### ISSUE THREAD

**Issue by shah-95** [ananjaser1211/FloydQ_Reports#262] opened 2021-04-21 21:42 UTC
**Describe the bug**

Phone freezes in screen off state, randomly. Probably after it has been on standby for a while without rebooting / has been in sleep for a while / recently has been charged in online state / phone is charging. Phone can be brought out of freezed state by repeatedly pressing power/home buttons sometimes but mostly it won't come out of it. And only hard reboot fixes it.

Note : Phone is at stock mostly, just rooted via magisk while kernel isn't messed with/changed. Hktweaks at default. Kernel gestures AREN'T enabled (since they caused similar problems per my experience)

Update : So, this time phone froze while in usage (browsing chrome) .. it went unresponsive and I pressed power button which surprisingly turned off the screen even in that frozen state and then it got frozen in that blackscreen. I tried repeatedly pressing home and power key and after some 10 minutes of hardship it again turned the screen on in a very slow motion and I noticed that wallpaper went black (was using infinity wallpaper). Phone was very sluggish when it came out of this state. I took logs at this moment, will post them too.

**To Reproduce**

Mostly at random, but happens mostly when
1. Phone is on standby for long
2. Phone is in sleep for long
3. Has been recently charged (while phone turned on)
4. Phone is on charge
5. While browsing chrome

**Expected behavior**

Phone shouldn't freeze like that. When I flashed rom fresh, this wasn't happening initially. But recently after many days have passed, this issue has been increasing frequency slowly. At start once in a day or two wasn't a bother. But now it happened multiple times.

**Smartphone :**

 - Device: Galaxy S7 Edge
 - Model: G935FD

**Additional context**

- Gathered some logs after I successfully brought phone out of freeze.
[logcat.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6354076/logcat.txt)
[dmesg.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6354087/dmesg.txt)
[last_kmsg.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6354082/last_kmsg.txt)

**New logs :**

[dmesg.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6360202/dmesg.txt)
[last_kmsg.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6360203/last_kmsg.txt)
[logcat.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6370467/logcat.txt)

**Edit 2 : Can confirm that changing kernel to morokernel 8.7 solves this issue as well as offline battery percentage mismatch**

**Comment by Skyterix1991** [comment] 2021-05-29 19:13
@ananjaser1211

I can confirm that is an issue.
I have encountered this pattern both on V5 and V6. After installation ROM works really smooth, nothing hangs all apps installed and working great, but after a while (can't put a date on it) it starts to freeze in apps. And then after a little longer, the whole system starts to have weird freezing fits. It randomly starts to have a BIG performance hit like for example I click a power button and have to wait a minute or two for it to light the screen and UI keep crashing. In this state phone basically is unusable it is hard to even get to restart it (and I have a feeling hard restarts may not be such a good idea so frequently so I try to avoid it). For me, it looks like something is just eating CPU and not letting go for a while.

I think once I just left it be and it resolved itself, so that is weird.
I attached logs but I don't think I had any freeze since the last restart, I will try to pull logs when the phone gets in that state.

[log_All.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/6565230/log_All.txt)

**Comment by V3rB0se** [comment] 2021-12-13 18:59
same
[Log_All](https://github.com/ananjaser1211/FloydQ_Reports/files/7704551/log_All.log)

**Comment by ananjaser1211** [comment] 2022-07-01 14:52
Please let me know if the issue persists in v7.0 with new logs.

**Comment by gorandroid** [comment] 2022-07-08 13:44
On v6 this happens to me only when i use hktweaks along with gestures enabled... anyone else?

**Comment by ananjaser1211** [comment] 2023-04-24 17:22
So after long debugging, it seems that the time the black screen delay happens is when sensor hub dies and takes 5+ seconds to wakeup, sometimes does not wakeup at all.

to confirm this, when black screen occurs or wake up delay happens, after struggling to wake up the phone do *#0*# in dialer > sensorhubtest > screen will blank, wake it up after struggling again, and your sensorhub will report FAIL

Also, lunching camera once seems to basically fix the issue until it happens again, this is likely also why alarms sometimes dont wake up the phone

Working state :
![image](https://user-images.githubusercontent.com/25624482/234070494-428de32a-0c46-48b2-8207-11c9c92b167a.png)

Black screen state :

![image](https://user-images.githubusercontent.com/25624482/234070530-ecf4f3b9-cf75-4a05-afe0-7b100906b7e6.png)

**Comment by ananjaser1211** [comment] 2023-11-05 14:53
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172

* I made it so LHD service restarts after a successful boot, the black screen issue has not returned since, sensorshub no longer shows crashes, further more we switched to using stock S7/S7E sensor libs (which also fixes #181 ) and stock sensorhub libs which should be more stable. re-open if issue persists

**Closed by ananjaser1211** 2023-11-05 14:53 UTC
Labels: bug, unconfirmed fix
