### ISSUE TITLE
[BUG] Alarm bug

### ISSUE THREAD

**Issue by black4nothing** [ananjaser1211/FloydQ_Reports#259] opened 2021-04-10 10:33 UTC
FloydQ V6.0
Alarm wont ring it often work

I set up my alarm but it didnt ring.
I use this phone as a alarm clock and timer.
The aod is always on. I dont know if thats the issue or something...

Smartphone
SM-G935K

**Comment by Yves911** [comment] 2021-04-12 08:45
Got the same trouble this morning.
This issue seems to come with v6, (i was previously using V5 without this bug).
What kind of logs do we need here?

**Comment by ananjaser1211** [comment] 2021-04-13 06:10
im not sure honestly, i dont see why alarms are not working for some, by any chance is it only alarms that are not working, or entire system audio next morning.

also tried to change the alarm tone ?

need more input on this since i cant recreate the bug yet, so far all the alarms are working

**Comment by Yves911** [comment] 2021-04-13 19:19
So alarms were working fine with V5.
This morning again no alarm sound but the system audio was working fine.
I tried another tone for this morning but with no luck again.

I used to have the "no disturb" function activated during the night, i will stop it for this night and see if it helps (i already checked that alarm can trigger with the "no disturb" thing enabled).

Cheers
Yves

**Comment by ananjaser1211** [comment] 2021-04-13 21:38
No disturb should be fine with alarms, i honestly dont know what is going on, i will continue testing and see if i land at something.

**Comment by Yves911** [comment] 2021-04-14 19:24
I got sound with alarm this morning. Differences with yesterday DND disabled + 1 reboot yesterday evening.
As it is intermittent i can't say for sure that these 2 changes are linked to the root cause...

**Comment by Yves911** [comment] 2021-04-27 19:45
@ananjaser1211 hey, some fresh news.
Again this morning no sound for my alarm BUT it seems to me that the problem is that alarm hasn't been triggered.
Few minutes after that alarm should have been triggered i play audio files without any issue.

So to me i am under the impression that it's not an audio issue but something linked to a deep sleep mode or something like this...
How could i check that ?

**Comment by ananjaser1211** [comment] 2021-06-04 10:39
> @ananjaser1211 hey, some fresh news.
> Again this morning no sound for my alarm BUT it seems to me that the problem is that alarm hasn't been triggered.
> Few minutes after that alarm should have been triggered i play audio files without any issue.
> 
> So to me i am under the impression that it's not an audio issue but something linked to a deep sleep mode or something like this...
> How could i check that ?

Just read this, if there is audio, that is indeed not an audio issue as i thought, but something keeping the alarm app from running ? 

i will check it further after the rebases, might have been a bug that was fixed by samsung, lets see

**Comment by Yves911** [comment] 2021-06-04 20:02
thanks for the reply in the meantime i haven't encoutered this bug since few weeks so...

**Comment by mehdi-gh82** [comment] 2021-06-05 05:59
> FloydQ V6.0
> Alarm wont ring it often work
> 
> I set up my alarm but it didnt ring.
> I use this phone as a alarm clock and timer.
> The aod is always on. I dont know if thats the issue or something...
> 
> Smartphone
> SM-G935K

Hi 👋
When your phone on sound mode , The alarm works well
And when your phone on vibrate or silent mode , the alarm just vibrate and no any sound.
So You should always set your phone to sound mode.

**Comment by ananjaser1211** [comment] 2022-07-01 14:44
V7.0 includes new fixes for the freeze that caused alarms not to wakeup. if the issue presists please re-open with new logs / details.

**Closed by ananjaser1211** 2022-07-01 14:44 UTC
Labels: bug, Fixed in next release
