### ISSUE TITLE
[BUG] Gallery app labels won't stay hidden ('Videos', 'Favorites', 'Recent' and 'Suggested')

### ISSUE THREAD

**Issue by jozwety** [ananjaser1211/FloydQ_Reports#207] opened 2020-10-22 15:27 UTC
**Describe the bug**
In the gallery app the labels 'Videos', 'Favorites', 'Recent' and 'Suggested' are always showing. On my Galaxy Tab S4 (Android 10) is it not showing until you swipe down. In Android 9 it's hidden too. I did close the app, re-installed the ROM, did a wipe, cleared the cache, but nothing seems to fix it. I did try to add more Albums, so it may hide because there are more items to show. That didn't solve the problem eighter. Even uninstalling the Gallery app and reinstalling a newer or older version did not work. It must be something in the ported ROM that causes the labels to always show?

**To Reproduce**
1. Open Gallery app
2. Swipe up, so the labels are hidden
3. Close app and close in recent apps too
4. Open Gallery app --> labels are showing again

**Expected behavior**
I expected to not see the labels, because I swiped down and they where hidden when I closed the app. On an original Android 10 ROM (for example a Samsung Galaxy Tab S4 or Galaxy A50) the labels are hidden.

**Screenshots**
This it what it looks like when you open the app:
![Screenshot_20201022-172141_Gallery](https://user-images.githubusercontent.com/73300577/96893832-6d32fd80-148b-11eb-8fd9-b4d4b2464a8c.jpg)

When you swipe up, the labels are hiding. (Again showing when you open the app again). The labels should still be hidden when you open it again. This is what it looks like when you swipe up:
![Screenshot_20201022-172146_Gallery](https://user-images.githubusercontent.com/73300577/96893837-6dcb9400-148b-11eb-926f-767f95413faa.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930F

**Comment by SypeR54** [comment] 2020-10-22 19:00
It's not a bug. On updated versions of Q (OneUI 2.1/2.5) Gallery and R (OneUI 3.0) gallery it's not hiding. Especially on OneUI 3.0 gallery its not hiding even swiping between up and down.

**Comment by jozwety** [comment] 2020-10-22 22:05
> It's not a bug. On updated versions of Q (OneUI 2.1/2.5) Gallery and R (OneUI 3.0) gallery it's not hiding. Especially on OneUI 3.0 gallery its not hiding even swiping between up and down.
> 
> Please install the same version of Q Gallery on both device and check again.

On both my Galaxy S7 with FloydQ V4.0 (OneUI 2.1) ROM and Galaxy Tab S4 original Android 10 (OneUI 2.1) ROM are the same version installed (11.5.02.4).

So the Android version, OneUI version and Gallery app version are exactly the same on both devices.

Labels are hiding on my S7 and Tab S4 when they're in landscape mode. In portraite mode the labels are showing on both devices. Weird that you cant just hide them, but that's a design choice by Samsung then. 😓

**Comment by ananjaser1211** [comment] 2020-10-22 23:49
Yes this has bothered me too with the S9. the tabs refuse to hideas you would expect them to.

sadly not a rom bug, so ill be closing this issue. tho an annoying one that is for sure. id love to find a way to hide them when needed

**Closed by ananjaser1211** 2020-10-22 23:49 UTC
