### ISSUE TITLE
[BUG] In a Smart View Function

### ISSUE THREAD

**Issue by JeffS2Duda** [ananjaser1211/FloydQ_Reports#69] opened 2020-04-30 01:48 UTC
The function of mirroring the TV screen on the Smartphone does not work correctly.
When I use the function to mirror the TV screen on my Smartphone, I can only see some TV options on my Smartphone screen when I press the back key.
The Smartphone does not display the TV image and the TV sound does not come out either.
Note: The TV control buttons are still working in this mode.

I already tried to enter this mode using the smart things application and the button bar smart view function, both gave the same result.

This function is very useful when you have to go to another room in the house and you are watching some TV programming.

Some Screenshots:
http://imgur.com/a/vmQZz2i

 - Device: Galaxy S7E
 - Model: G935F
Note: I did a clean install deleting everything from the phone, installed the indicated TWRP and I already have the new Kernel V3.5

I don't know if there is a need for Logs, but at the moment I have no access to a computer.  if it is possible to do it by cell phone, I will.

**Comment by KiLLSwitCH997** [comment] 2020-04-30 01:53
Well,That function isn't working since Pie because S7/S7E isn't capable of running it. You only can mirror Phone to TV.

**Comment by JeffS2Duda** [comment] 2020-04-30 01:57
Only in this version and in the Pie version that don't work correctly?
Because I used this function on Android 8.
My wife's cell phone is still with Rom Stock on Android 8 and I can post images that the function works on Android 8 if you needed.

**Comment by ananjaser1211** [comment] 2020-04-30 06:30
I’ll see what I can do.

Smartview behavior changes a lot rom Oreo to pie and up so the implementation that was used before might no longer work

**Comment by JeffS2Duda** [comment] 2020-04-30 13:44
I see, thank's a lot anyway ^-^

**Comment by ananjaser1211** [comment] 2020-05-01 12:53
After talking to a friend (who owns an S8/S9 And and an S10) the mirror from TV to device seem to break after root ? i am not sure what is the cause just yet, but the feature does not work on those devices as well.

the feature is there, just cant connect. i am wondering if it is some root protection set in place (we already need a patch to make normal smartview work after rooting)

ill more into it but it seems to be a dead end

**Comment by JeffS2Duda** [comment] 2020-05-03 05:05
I didn't notice it when I did the Root on my Rom stock, so I can't confirm it.  But I will search if there is any way around this, if it works in this ROM it will be wonderful.
Thank you so much for your help and your time :D

**Comment by ananjaser1211** [comment] 2020-05-12 19:12
After trying alot, this feature seems to be hardware based. ill close this issue unless i find something new

**Closed by ananjaser1211** 2020-05-12 19:12 UTC
