### ISSUE TITLE
[BUG] Accidentally captured screenshots

### ISSUE THREAD

**Issue by NELSON777A** [ananjaser1211/FloydQ_Reports#170] opened 2020-08-19 15:36 UTC
Esto ha sido un problema para mi porque adcidentalmente tomo capturas de pantalla  
Y queria ver  si depronto podria  poner la captura de pantalla con el boton de volumen - home y power
**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by SypeR54** [comment] 2020-08-19 15:42
I can't understand your issue clearly because of poor translate engines. But as i understand you want to switch your screenshot key combination with" Power and Home" button instead of "Power and Vol Down". Isn't it?

**Comment by NELSON777A** [comment] 2020-08-19 15:45
Ok

**Comment by SypeR54** [comment] 2020-08-19 16:02
Instead of "Ok", do you have any plan to explain yourself? If your answer is "Yes", then i'll wait your explanation. If your answer is "No", then i'm gonna close this issue ticket. Because it's not a bug or issue.

Note: Also, there is a alternative ways to taking a screenshot on Floyd Q rom. Like "Hi Bixby, take a screenshot" or swiping hand palm over screen.

**Comment by NELSON777A** [comment] 2020-08-19 16:07
Si 
Porque  estoy tomando muchas fotos adcidentales en estos dias

**Comment by NELSON777A** [comment] 2020-08-19 16:21
Pues seria bueno que pusieran la captura de  pantalla deslisando la mano

**Comment by SypeR54** [comment] 2020-08-19 19:19
This features already added in Floyd Q rom. Because they are "Samsung's own" features. All Samsung devices has these gestures. To enable swiping hand to screenshot, follow this steps:

- Open "Settings" app.
- Scroll down to "Advanced Settings" and click on it.
- Scroll down to "Gestures and Signs" and click on it.
- Find "Palm swipe to capture" and enable it.

After these steps, you can also take screenshots by your palm movements. Also **we can't do anything** about your accidentally captured screenshots by "Volume Down + Power Key" combination. It's classical Android key shortcut, not us or Samsung.

I'm closing this issue report because it's not a ROM issue.

**Closed** 2020-08-19 19:19 UTC
Labels: invalid

**Comment by NELSON777A** [comment] 2020-08-19 20:35
Y si lo dejan con bajar volumen + tecla inicio + tecla de encendido

**Comment by SypeR54** [comment] 2020-08-19 21:03
No, you can't change it to another combination.
