### ISSUE TITLE
[BUG] SoundAssistant resetting equalizer

### ISSUE THREAD

**Issue by souzajerry** [ananjaser1211/FloydQ_Reports#204] opened 2020-10-07 01:32 UTC
Hello again anan, I have been thinking for a long time how to report this "bug", what happens is that the soundassistant whenever I define a custom equalizer in it, after ten seconds with the screen off it goes back to the stock. Even using the floating button or the theme. I am facing this error since v1. And I wish there was a solution because the soundassistant would help me a lot on the day. Thanks again for everything you have done for the community and sorry for my bad English.

**Smartphone**
 - Device: [Galaxy S7 Edge]
 - Model: [G935F]

**Comment by ananjaser1211** [comment] 2020-10-07 06:10
I have this behaviour only when using V4A Or power AMP. by default sound assistant config retains .

**Comment by souzajerry** [comment] 2020-10-07 12:00
what happens to me is that i set an equalizer setting in soundassistant and when i access the equalizer through the settings it is in the stock. Would have somehow attach a video from the screen?

**Comment by souzajerry** [comment] 2020-10-08 18:31
through the screenshots to understand the problem?

**Comment by ananjaser1211** [comment] 2020-10-08 19:23
i will look into it once i have time, i noticed similar thing on my S9 when using goodlock sound assistant module, the EQ is different from the system EQ. so it could be a Oneui bug

**Comment by souzajerry** [comment] 2020-10-09 02:43
do everything in your time, thanks for your attention

**Comment by ananjaser1211** [comment] 2020-10-11 16:11
ok just confirmed. my S9 has seperate settings in soundalive and in soundassistant goodlock module. 

this seems to be normal behaviour from oneui 2 and not an S7 bug. ill close this issue

**Closed by ananjaser1211** 2020-10-11 16:11 UTC
