### ISSUE TITLE
[BUG] Battery issues or Phone Crashing not sure which one is it

### ISSUE THREAD

**Issue by RepotSirc** [ananjaser1211/FloydQ_Reports#101] opened 2020-05-31 01:05 UTC
**Describe the bug**
My phone suddenly turns off even with 65% battery, I charged it to at least 4% then let it discharge. After the 4% battery is fully discharged, I charged the phone again and battery showed 65%+, I left it overnight and upon waking up in the morning I still have less than 20%.

**To Reproduce**
I do not think there is way to reproduce other than taking a video but I am not sure if that's is even doable because it does not happen in a specific time I would need capture video of my phone for the whole day to capture it.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 Edge
 - Model:  G965F

**Additional context**

**Comment by ananjaser1211** [comment] 2020-05-31 09:32
Calibration issue if i have to guess, i dont see how i am supposed to approach this issue.

try to recalibrate your battery and do few charge cycles

**Comment by ananjaser1211** [comment] 2020-06-03 10:41
Well any updates ? more info etc ?

**Comment by RepotSirc** [comment] 2020-06-05 07:43
I have tried draining and charging for multiple days and still the same.

Now I am trying a battery calibration app from Google Play store and the difference in the battery is still off by 9% (Battery level when being charge vs When Phone is turned on)

**Comment by ananjaser1211** [comment] 2020-06-05 09:48
Are you sure your battery is not just damaged / worn out ? 
de-sync exists, but at most %5 . having 25% mismatch is very abnormal, and i have yet to see a case of it.

**Comment by Malocekr** [comment] 2020-06-09 13:32
My phone has crashing too.
I take my phone in charge while i sleep, and wake up, i don't use my phone, because it's crash (Black screen/led green)

**Comment by ananjaser1211** [comment] 2020-06-09 14:06
> My phone has crashing too.
> I take my phone in charge while i sleep, and wake up, i don't use my phone, because it's crash (Black screen/led green)

overnight crash discussion is #7

This issue is still uncelar whether it is related to the overnight bug, or its some battery flaw.

becasue the reported case does not suite #7 neither it is a bug anyone in my testing team can reproduce. 

im closing this to avoid future confusion. if OP has more details please share them

**Closed by ananjaser1211** 2020-06-09 14:06 UTC
